<p>[gettext]In the summer of 2008, based on a freelancing job, Brandon Evans decided to write yet another PHP forum system. When enlisting Chris Santiago to help, Chris stated that he was working on another forum system, Parasol Boards, in Python, but that he would help me out if necessary.[/gettext]</p>

<p>[gettext]Brandon first wanted to focus on the templating system of the forum. He wanted the user to be able to move around the site as much as they wanted without having to touch the code. The concept started very rough, working through a regular expression that matched two keywords and their contents, and that replaced the whole block with something based on the contents. The replacements were done independently of one another to ensure that nothing would be transformed twice. Eventually the regular expression was substituted with search functions, but the replacing remained the core of the project. Very messy, but at that point, it looked OK.[/gettext]</p>

<p>[gettext]On October 10, 2008, Brandon figured that because so much time was focused on the templating system that he figured he should abandon the forum and devote all of his resources to the templating system. He named it SUIT (Scripting Using Integrated Templates), which Chris approved of. He later planned on picking it back up in a project called CAPE (Community Application Proven Effective), but quickly scrapped it. At the same time, the two worked on a subproject called TIE (Template Integration Environment), which was supposed to be a way of managing templates on the web. The code was very messy and drawn out, which eventually frustrated Chris to the point where he took hiatus from the project. In the end, TIE was discontinued as it was hard to maintain, and that we figured the user could implement their own way of managing templates if they deemed fit.[/gettext]</p>

<p>[gettext]Later, after much debate, Alex Munroe finally got the concept of parsing through Brandon's thick skull. Afterwards, recursion was made much easier. From there, he tidied up the syntax, made the rules for the transformation customizable, and overall solidified the concept of SUIT. He also started working on a Python version. Chris soon rejoined, this time as a harsh critic. For every stupid thing Brandon suggested, Chris negated, and everything good Brandon said, Chris supported. It turned out to be a very strong dynamic.[/gettext]</p>

<p>[gettext]After version 1.3.4, Brandon finally started using SVN. With it, he introduced attributes, separated template retrieval from the system, optimized the system, and much more. In fact, there was apparently so much to tidy up that he never wanted to make another release until he deemed the project solid. Along with this, he decided to redo the site and documentation. During this period, Brandon also developed SLACKS (SLACKS Lets Application Coders Know SUIT), which could be used to debug SUIT. He expects release of SUIT 2.0.0 somewhere in the summer.[/gettext]</p>

<p>[gettext]Chris still works on Parasol Boards, which now uses SUIT. He has yet to announce a release date for it. Brandon has given up his original vision of a forum system, but might work on Parasol Boards if time permits.[/gettext]</p>